import fs from "node:fs";
import path from "node:path";
const envPath=path.resolve(process.cwd(),".env.local");
if(fs.existsSync(envPath)){for(const line of fs.readFileSync(envPath,"utf8").split(/\r?\n/)){const match=line.match(/^\s*([^#][^=]+)=(.*)$/);if(match)process.env[match[1].trim()]=match[2].trim().replace(/^['"]|['"]$/g,"").replace(/\s+#.*$/,"");}}
const only=process.argv.find(arg=>arg.startsWith("--only="))?.split("=")[1];
const safeError=async response=>{const text=await response.text();try{const parsed=JSON.parse(text);return parsed?.error?.message||parsed?.message||`HTTP ${response.status}`;}catch{return text.slice(0,180)||`HTTP ${response.status}`;}};
async function anthropic(){const key=process.env.ANTHROPIC_API_KEY;if(!key)return{service:"anthropic",ok:false,error:"ANTHROPIC_API_KEY 미설정"};if(!/^[\x20-\x7E]+$/.test(key))return{service:"anthropic",ok:false,error:"ANTHROPIC_API_KEY에 ASCII가 아닌 문자가 포함되어 있습니다. 키를 다시 복사해 주세요.",credential:{length:key.length,nonAsciiCharacters:[...key].filter(char=>char.charCodeAt(0)>127).length}};const started=Date.now();try{const response=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"},body:JSON.stringify({model:process.env.CLAUDE_MODEL||"claude-opus-5",max_tokens:8,messages:[{role:"user",content:"OK만 답하세요."}]})});return response.ok?{service:"anthropic",ok:true,status:response.status,elapsedMs:Date.now()-started,requestId:response.headers.get("request-id")}:{service:"anthropic",ok:false,status:response.status,elapsedMs:Date.now()-started,error:await safeError(response)};}catch(error){return{service:"anthropic",ok:false,elapsedMs:Date.now()-started,error:error instanceof Error?error.message:String(error)};}}
async function policy(){const key=process.env.POLICY_NEWS_API_KEY;if(!key)return{service:"policy_news",ok:false,error:"POLICY_NEWS_API_KEY 미설정"};const end=new Date(),start=new Date();start.setDate(end.getDate()-2);const keyOf=d=>`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;const params=new URLSearchParams({serviceKey:decode(key),numOfRows:"1",pageNo:"1",startDate:keyOf(start),endDate:keyOf(end)});const started=Date.now();try{const response=await fetch(`https://apis.data.go.kr/1371000/policyNewsService2/policyNewsList2?${params}`);const text=await response.text();const code=text.match(/<resultCode>(.*?)<\/resultCode>/)?.[1];const message=text.match(/<resultMsg>(.*?)<\/resultMsg>/)?.[1];const count=[...text.matchAll(/<NewsItem>/g)].length;return{service:"policy_news",ok:response.ok&&(!code||code==="0"),status:response.status,elapsedMs:Date.now()-started,resultCode:code||null,resultMessage:message||null,itemsInProbe:count,quotaHeaders:{limit:response.headers.get("x-ratelimit-limit"),remaining:response.headers.get("x-ratelimit-remaining"),reset:response.headers.get("x-ratelimit-reset")}};}catch(error){return{service:"policy_news",ok:false,elapsedMs:Date.now()-started,error:error instanceof Error?error.message:String(error)};}}
async function gemini(){const key=process.env.GEMINI_API_KEY,model=process.env.GEMINI_MODEL||"gemma-4-26b-a4b-it";if(!key)return{service:"google_search_grounding",ok:false,error:"GEMINI_API_KEY 미설정"};const started=Date.now();try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:"오늘 기준 대한민국의 최저임금을 검색하고 출처와 함께 답하세요."}]}],tools:[{google_search:{}}],generationConfig:{maxOutputTokens:256}})});if(!response.ok)return{service:"google_search_grounding",ok:false,status:response.status,model,elapsedMs:Date.now()-started,error:await safeError(response)};const data=await response.json();const grounding=data?.candidates?.[0]?.groundingMetadata;const chunks=grounding?.groundingChunks?.filter(chunk=>chunk?.web?.uri)||[];return{service:"google_search_grounding",ok:chunks.length>0,status:response.status,model,elapsedMs:Date.now()-started,generationOk:true,groundingOk:chunks.length>0,sourceCount:chunks.length,error:chunks.length?undefined:"응답은 생성됐지만 Google 검색 출처 메타데이터가 없습니다."};}catch(error){return{service:"google_search_grounding",ok:false,model,elapsedMs:Date.now()-started,error:error instanceof Error?error.message:String(error)};}}
function decode(value){try{return decodeURIComponent(value);}catch{return value;}}
const checks=only==="anthropic"?[anthropic()]:only==="policy"?[policy()]:only==="gemini"?[gemini()]:[anthropic(),gemini(),policy()];
const results=await Promise.all(checks);console.log(JSON.stringify({checkedAt:new Date().toISOString(),results},null,2));process.exitCode=results.every(result=>result.ok)?0:1;
